version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: note-user
      POSTGRES_PASSWORD: note-password
      POSTGRES_DB: note
    volumes:
      - ./course/init.sql:/docker-entrypoint-initdb.d/init.sql
      - course-db-data:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "note-user"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: grpc
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: note
      DB_USER: note-user
      DB_PASSWORD: note-password
    ports:
      - "50051:50051"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  envoy:
    image: envoyproxy/envoy:v1.29.0
    volumes:
      - ./frontend/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
    depends_on:
      - server
    container_name: envoy_proxy
    networks:
      - app-network

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - envoy
    container_name: frontend_app
    networks:
      - app-network
    # Добавляем команду для проверки контейнера после запуска
    command: sh -c "npm --version && npx --version && npx serve dist -l 3000"

volumes:
  course-db-data:

networks:
  app-network:
    driver: bridge
