version: '3.8'

volumes:
  postgres_volume:

services:
  pg:
    image: postgres:14-alpine3.17
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  migrator:
    build:
      context: postgres
      dockerfile: migration.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg

  grpc_server:
    build:
      context: grpc
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - pg
    environment:
      PG_DATABASE_NAME: note
      PG_USER: note-user
      PG_PASSWORD: note-password
      PG_PORT: 54321
      MIGRATION_DIR: ./migrations