name: CI

on:
  push:
    branches: [main, master, To-Do_List]
  pull_request:
    branches: [main, master, To-Do_List]

env:
  REGISTRY: "cr.selcloud.ru/registry"
  IMAGE_NAME: "crud-server"
  CONTAINER_NAME: "crud-server-container"

jobs:
  Install-Docker-Compose:
    runs-on: ubuntu-latest
    steps:
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

  build-and-push:
    runs-on: ubuntu-latest
    needs: Install-Docker-Compose

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY

      - name: Build and Push Docker Images with Docker Compose
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker-compose -f docker-compose.yaml build
          docker-compose -f docker-compose.yaml push

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Deploy with Docker Compose
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker-compose -f docker-compose.yaml up -d